### ISSUE TITLE
Can you support multiple dex parsing?

### ISSUE THREAD

**Issue by payshin** [hsiafan/apk-parser#60]
Can you support multiple dex parsing? My system is Android 4.4, and I want to parse classes2.dex

**Comment by payshin** [comment]
My temporary solution is as follows,Hope to integrate into it to make it more beautiful。
byte[] data = apkFile.getFileData("classes2.dex");
                ByteBuffer buffer = ByteBuffer.wrap(data);
                DexParser dexParser = new DexParser(buffer);
                dexParser.parse();
                DexClass[] classes2 =dexParser.getDexClasses();

**Comment by payshin** [comment]
@clearthesky Thank you! apk-parser 2.2.1 version supports multi dex files, I have found new problems, parse of the inner class ranking problem, for example, I parse the WeChat 6.5.10 version of En_5b8fbb1e$a$55 in front of En_5b8fbb1e$a$142 in the back, and I parse the WeChat 6.5.8 version of En_5b8fbb1e$a$142 in front of En_5b8fbb1e$a$55 in the back, only the inner class sort is not uniform, the other class of normal. Thank you for your trouble. Thank you!

**Comment by clearthesky** [comment]
DexParser just follow the order dex file store classes, so it's determined by build tools.
