### ISSUE TITLE
If the apk has multiple signature, ApkParser only can get one signature certificate

### ISSUE THREAD

**Issue by ebert001** [hsiafan/apk-parser#65]
If the apk has multiple signature, ApkParser only can get one signature certificate. The problem code:
`protected byte[] getCertificateData() throws IOException {
        ZipEntry entry = null;
        Enumeration<? extends ZipEntry> enu = zf.entries();
        while (enu.hasMoreElements()) {
            ZipEntry ne = enu.nextElement();
            if (ne.isDirectory()) {
                continue;
            }
            if (ne.getName().toUpperCase().endsWith(".RSA") || ne.getName().toUpperCase().endsWith(".DSA")) {
                entry = ne;
                break;
            }
        }
        if (entry == null) {
            return null;
        }
        return Utils.toByteArray(zf.getInputStream(entry));
    }`

[app-Pos_1_1_20170619_signed.apk.zip](https://github.com/hsiafan/apk-parser/files/1516429/app-Pos_1_1_20170619_signed.apk.zip)
You can rename to app-Pos_1_1_20170619_signed.apk.zip to app-Pos_1_1_20170619_signed.apk, then open and check it.

**Comment by ebert001** [comment]
@hsiafan

**Comment by hsiafan** [comment]
Now version 2.4.2 add getAllCertificateMetas method to get all certificates info.
