### ISSUE TITLE
fail parse minSdkVersion

### ISSUE THREAD

**Issue by Kecin-Chen** [hsiafan/apk-parser#86]
using version:
  `compile group: 'net.dongliu', name: 'apk-parser', version: '2.6.5'`
test code:
  String minSdkVersion= apkMeta.getMinSdkVersion();`
 java version:
  "1.8.0_152"
![default](https://user-images.githubusercontent.com/30857278/53074070-cb744400-3524-11e9-97f4-c6b8e851262d.PNG)

The minSdkVersion is defined in the manifestXml, but is empty when parsing.

**Comment by Kecin-Chen** [comment]
@hsiafan

**Comment by hsiafan** [comment]
would you please provide a apk file which can trigger this issue?

**Comment by Kecin-Chen** [comment]
Ok.Thank you.

**Comment by Kecin-Chen** [comment]
@hsiafan 
Here is the download url of the apk.You can try it.
http://appstorecos.coolyun.com/group5/dev_upload/f7/f7816568d8e99819687bdedb0e2a7c5c.apk

**Comment by hsiafan** [comment]
should be fixed in new version 2.6.9

**Comment by Kecin-Chen** [comment]
Ok,thank you!
