### ISSUE TITLE
got an Exception: java.lang.NoSuchMethodError when using apkFile.getApkSingers(), version: 2.6.5

### ISSUE THREAD

**Issue by Kecin-Chen** [hsiafan/apk-parser#87]
like the problem in version 2.5.0, I have got an Exception: java.lang.NoSuchMethodError when using apkFile.getApkSingers() ,version 2.6.5,with jdk_1.8_152. How can I solve it,use jdk1.9?@hsiafan

**Comment by hsiafan** [comment]
Please try latest version 2.6.6.
